<div class="timer-group">
	<div class="container">
		<div class="row">
			<div class="col-md-6 col-sm-12 col-xs-12">
				<?php echo $this->getLayout()->createBlock('Plazathemes\Pricecountdown\Block\Pricecountdown')->setTemplate('saleslider.phtml')->toHtml();?> 
			</div>
			<div class="col-md-6 col-sm-12 col-xs-12">
				<?php echo $this->getLayout()->createBlock('Plazathemes\Featureproductslider\Block\Featureproductslider')->setTemplate('featureproductslider.phtml')->toHtml();?>
			</div>
		</div>
	</div>
</div>